### Create Product
POST http://localhost:8080/api/v1/product
Content-Type: application/json

{
  "name": "Product Name",
  "description": "Product Description",
  "price": 20.99,
  "stock": 10,
  "supplierId": 100
}