### Create Product
POST http://localhost:8080/api/v1/product
Content-Type: application/json

{
  "name": "Fritadeira elétrica",
  "description": "Fritadeira elétrica 220V",
  "price": 120.99,
  "stock": 7,
  "supplierId": 1
}

### Get Products
GET http://localhost:8080/api/v1/product?name=gi
